version: "2.0"

services:
  pgadmin:
    image: dpage/pgadmin4:5
    restart: always
    ports:
      - 8000:80
    links:
      - db:db
    environment:
      - PGADMIN_DEFAULT_EMAIL=john@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin

  db:
    image: postgres:13.2
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  server:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - 3001:3001
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=admin
      - PG_PASSWORD=admin
      - PG_DATABASE=dev
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

volumes:
  db:
    driver: local
